### ISSUE TITLE
The requested module 'neis.ts' does not provide an export named 'default'

### ISSUE THREAD

**Issue by minmoong** [star0202/neis.ts#20]
```javascript
import Neis from 'neis.ts'
import { Logger } from 'tslog'

const neis = new Neis({
  key: 'API KEY',
  logger: new Logger(),
})

neis
  .getSchool({
    ATPT_OFCDC_SC_CODE: '시도교육청코드',
    SD_SCHUL_CODE: '표준학교코드',
  })
  .then((res) => {
    console.log(res)
  })
  .catch((err) => {
    console.error(err)
  })
```

위 예제를 typescript 환경에서 ts-node를 사용하여 실행한 결과 다음과 같은 오류가 발생했습니다.

![스크린샷 2023-10-28 201531](https://github.com/star0202/neis.ts/assets/62737839/24d550c2-3c85-4882-a564-8004397f1c50)

**package.json**
```
{
  "type": "module",
  "dependencies": {
    "neis.ts": "^1.3.0"
  },
  "devDependencies": {
    "@types/node": "^20.8.9",
    "typescript": "^5.2.2"
  }
}
```

**tsconfig.json**
```
{
  "compilerOptions": {
    "lib": ["ES6", "DOM"],
    "moduleResolution": "Node",
    "declaration": true,
    "strict": true,
    "target": "ES6",
    "module": "ES6"
  },
  "include": ["src/index.ts"],
  "ts-node": {
    "esm": true
  }
}
```

왜 이런지 알 수 있을까요?

**Comment by minmoong** [comment]
index.js로 실행하니 다음과 같은 에러도 발생합니다.

![스크린샷 2023-10-28 201531](https://github.com/star0202/neis.ts/assets/62737839/429b8730-aa48-426c-a3df-da64790c376b)

모듈 설정 문제인 것 같습니다.

**Comment by star0202** [comment]
오류를 재현할 수 없습니다. 어떤 명령어를 사용해 실행하셨는지 첨부해 주실 수 있으실까요?

**Comment by minmoong** [comment]
![스크린샷 2023-10-29 113204](https://github.com/star0202/neis.ts/assets/62737839/b2cc860a-f9b2-473f-a38a-f39609404002)

![스크린샷 2023-10-29 113145](https://github.com/star0202/neis.ts/assets/62737839/9b377a32-4f38-4bc9-a695-2397bf3a5ec8)

위 명령어로 실행했습니다.. 그런데 어제와는 다른 오류가 발생하네요..

![스크린샷 2023-10-29 113316](https://github.com/star0202/neis.ts/assets/62737839/87871001-a836-4aed-b764-67e56ce066e4)

neis.ts 해당 모듈의 dist 폴더에 있는 index.js를 보면 Neis 클래스를 default로 내보내고 있는데, 이것이 문제인가 싶어서 import 부분을 다음과 같이 수정해봐도 같은 오류가 발생합니다.

```javascript
import { default as Neis } from 'neis.ts'
```

nodejs   -  v18.18.0
tsc         -  v5.2.2
ts-node -  v10.9.1

버전의 문제가 의심되긴 하네요..ㅠ

**Comment by minmoong** [comment]
해결했습니다..! nodejs, typescript를 최신 버전으로 올렸더니 해결됐습니다.
